In [1]:
import numpy as np

### *Criando matriz*

In [2]:
a = np.array([1, 2, 3]) #função com lista de 3 elementos
print(a)

print("\n")

b = np.array([(2, 5, 7), (5, 3, 9)])
print(b)

print("\n")

c = np.zeros((4, 3))
print(c)

[1 2 3]


[[2 5 7]
 [5 3 9]]


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### *Manipulando matriz*

In [3]:
d = np.eye(5)
print(d)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [4]:
b.sum() #soma da matriz

31

In [5]:
b.mean() #média da matriz

5.166666666666667

In [6]:
b.std() #desvio padrão

2.3392781412697